import * as Sharing from "expo-sharing";
import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, Text, View } from "react-native";
import { useFocusEffect } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { clearHistory, loadHistory, type HistoryItem } from "@/lib/job-history";

export default function HistoryScreen() {
  const [items, setItems] = useState<HistoryItem[]>([]);
  const reload = useCallback(() => { loadHistory().then(setItems); }, []);
  useFocusEffect(useCallback(() => { reload(); }, [reload]));
  async function share(item: HistoryItem) { if (!(await Sharing.isAvailableAsync())) return Alert.alert("Paylaşım kullanılamıyor"); await Sharing.shareAsync(item.outputUri, { dialogTitle: "Oluşturulan APK’yı kaydet veya paylaş", mimeType: "application/vnd.android.package-archive" }); }
  function clear() { Alert.alert("Geçmişi temizle", "Yalnızca yerel kayıt listesi silinir; APK dosyaları uygulama verisi temizlenene kadar kalır.", [{ text: "Vazgeç", style: "cancel" }, { text: "Temizle", style: "destructive", onPress: () => clearHistory().then(reload) }]); }
  return <ScreenContainer className="px-5"><View style={styles.header}><View><Text style={styles.title}>İşlem geçmişi</Text><Text style={styles.subtitle}>Bu cihazda oluşturulan son APK çıktıları.</Text></View>{items.length > 0 && <Pressable onPress={clear}><Text style={styles.clear}>Temizle</Text></Pressable>}</View><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} ListEmptyComponent={<View style={styles.emptyCard}><Text style={styles.emptyTitle}>Henüz işlem yok</Text><Text style={styles.emptyText}>Ana ekrandan bir APK paketi seçip işlemi başlattığınızda çıktılar burada görünür.</Text></View>} renderItem={({ item }) => <View style={styles.row}><View style={styles.icon}><Text style={styles.iconText}>APK</Text></View><View style={styles.copy}><Text style={styles.name} numberOfLines={1}>{item.outputName}</Text><Text style={styles.meta}>{new Date(item.createdAt).toLocaleString("tr-TR")} · {item.dexPatched} DEX</Text></View><Pressable onPress={() => share(item)} style={styles.share}><Text style={styles.shareText}>Paylaş</Text></Pressable></View>} /></ScreenContainer>;
}
const styles: Record<string, any> = { header: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between", paddingBottom: 18, paddingTop: 12 }, title: { color: "#14213D", fontSize: 25, fontWeight: "800" }, subtitle: { color: "#5D6B82", fontSize: 13, marginTop: 5 }, clear: { color: "#B3261E", fontSize: 13, fontWeight: "700", paddingTop: 7 }, list: { gap: 10, paddingBottom: 20 }, row: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D7E0EA", borderRadius: 16, borderWidth: 1, flexDirection: "row", gap: 10, padding: 12 }, icon: { alignItems: "center", backgroundColor: "#D7F4F7", borderRadius: 10, height: 40, justifyContent: "center", width: 40 }, iconText: { color: "#00646E", fontSize: 10, fontWeight: "900" }, copy: { flex: 1, gap: 4 }, name: { color: "#14213D", fontSize: 13, fontWeight: "700" }, meta: { color: "#5D6B82", fontSize: 10 }, share: { backgroundColor: "#EFFBFC", borderRadius: 9, paddingHorizontal: 10, paddingVertical: 8 }, shareText: { color: "#007E8A", fontSize: 11, fontWeight: "800" }, empty: { flexGrow: 1, justifyContent: "center" }, emptyCard: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D7E0EA", borderRadius: 18, borderStyle: "dashed", borderWidth: 1, gap: 7, padding: 24 }, emptyTitle: { color: "#14213D", fontSize: 16, fontWeight: "800" }, emptyText: { color: "#5D6B82", fontSize: 13, lineHeight: 19, textAlign: "center" } };
